version: "0.1"

x-database-config-data:
  &postgres-connection-data
  environment:
    POSTGRES_DB: "main"
    POSTGRES_USER: "user"
    POSTGRES_PASSWORD: "password"

x-pgadmin-dashboard-data:
  &pgadmin-dashboard-data
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@admin.com
    PGADMIN_DEFAULT_PASSWORD: secret
    PGADMIN_LISTEN_PORT: 80

x-client-backend-data:
  &client-backend-data
  environment:
    server.port: 8081
    spring.kafka.bootstrap-servers: localhost:9092
    spring.datasource.url: jdbc:postgresql://localhost:5432/main
    spring.datasource.username: admin@admin.com
    spring.datasource.password: secret

x-message-backend-data:
  &message-backend-data
  environment:
    server.port: 8080
    spring.kafka.bootstrap-servers: localhost:9092
    spring.data.redis.host: localhost
    spring.data.redis.port: 6379

services:
  postgres:
    container_name: postgres_db
    image: postgres:13.3
    restart: always
    <<: *postgres-connection-data
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.5
    <<: *pgadmin-dashboard-data
    ports:
      - "5000:80"
    volumes:
      - /var/lib/pgadmin

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  client-service:
    container_name: docdotdev_client_service
    image: docdotdev_client_backend
    build:
      context: backend/client-service
      dockerfile: Dockerfile
    <<: *client-backend-data
    ports:
      - "8081:8081"

  message-service:
    container_name: docdotdev_message_service
    image: docdotdev_message_backend
    build:
      context: backend/message-service
      dockerfile: Dockerfile
    <<: *message-backend-data
    ports:
      - "8080:8080"


